name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: pip install -r requirements.txt; fi

    - name: Test with pytest
      run:  pytest

    - name: Ejecutar la app
      run: python app.py 
    
    - name: Simular el deploy
      run: echo "Simular que se esta desplegando"

    - name: Construir la imagen de Docker
      run: docker build -t ghcr.io/drewcrx/hello-andrew:1.0.0 .

    - name: Login en Github container registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
